//Data Cache Sequencer
//Sequencer: UVM Component responsible for managing the flow of transactions generated by UVM sequences

class data_cache_sequencer extends uvm_sequencer #(cache_seq_item); //Extend from the UVM Sequencer class
    `uvm_component_utils(data_cache_sequencer) //Call UVM component to register

    function new(string name = "data_cache_sequencer", uvm_component parent = null);
        super.new(name, parent);
    endfunction
endclass: data_cache_sequencer